version: 2
jobs:
  build-jpi:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Xmx768m -Xms256m -Xss1m -Dorg.gradle.parallel=false -Dorg.gradle.daemon=false"
    steps:
      - checkout
      - run: ./gradlew :menkins-plugin:jpi
      - store_test_results:
          path: plugin/build/test-results/test
          when: always
      # As the JAR was only assembled in the first build container, build/libs will be empty in all the other build containers.
      - store_artifacts:
          path: build/libs
  build-server:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    working_directory: ~/repo
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Xmx768m -Xms256m -Xss1m -Dorg.gradle.parallel=false -Dorg.gradle.daemon=false"
    steps:
      - checkout
      - run: ./gradlew :menkins-server:build
      - store_test_results:
          path: server/build/test-results/test
          when: always
      # As the JAR was only assembled in the first build container, build/libs will be empty in all the other build containers.
      - store_artifacts:
          path: build/libs
